name: Generate Breakout Game
on:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12 PM UTC
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cyprieng/github-breakout@v1.0.0
        with:
          github_username: SAFAL-MONDAL
      - name: Commit SVGs
        run: |
          mkdir -p assets
          mv output/light.svg assets/breakout-light.svg
          mv output/dark.svg assets/breakout-dark.svg
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/
          git commit -m "Update Breakout game" || echo "No changes to commit"
          git push
